#ifndef H3C_RC_H
#define H3C_RC_H

enum h3c_rc
{
    H3C_OK,
    H3C_NOMEM,
    H3C_ERROR,
    H3C_FAILED_PARSE,
    H3C_FAILED_READ_FILE,
    H3C_FAILED_UNPACK,
    H3C_FAILED_PACK,
    H3C_OUTRANGE,
    H3C_TIMEOUT,
    H3C_CANCELED,
    H3C_CONNRESET,
    H3C_CONNREFUSED,
    H3C_PIPE,
    H3C_ADDRNOTAVAIL,
};

#endif
