name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Apt update
        run: sudo apt-get update

      - name: Install openssl
        run: sudo apt-get install -y libssl-dev

      - name: Install nng
        run: sudo apt-get install -y libnng1 libnng-dev

      - name: Install git
        run: sudo apt-get install -y git

      - name: Install cmake
        run: sudo apt-get install -y cmake

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DENABLE_ALL_WARNINGS=ON

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release --rerun-failed --output-on-failure

      - name: CPack
        working-directory: ${{github.workspace}}/build
        run: cpack

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ${{github.workspace}}/build/package/*
