name: Test

on: push

jobs:
  test:
    name: Test on ${{ matrix.os }} with build type ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v3

      - name: Apt update
        run: sudo apt-get update

      - name: Install libcurl4
        run: sudo apt-get install -y libcurl4 libcurl4-openssl-dev

      - name: Install python
        run: sudo apt-get install -y python3-venv python3-pip

      - name: Install git
        run: sudo apt-get install -y git

      - name: Install cmake
        run: sudo apt-get install -y cmake

      - name: Install pipx
        run: python3 -m pip install --user -U pipx

      - name: Install eviltest
        run: curl -fsSL "https://app.danilohorta.me/eviltest" | bash

      - name: Setup eviltest path
        run: |
          echo "$HOME/.bats/bin" >> $GITHUB_PATH
          echo "BATS_LIB_PATH=$HOME/.bats/lib" >> $GITHUB_ENV

      - name: Configure CMake
        if: runner.os == 'Linux'
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DUSE_SANITIZER='Address;Undefined' -DENABLE_ALL_WARNINGS=ON

      - name: Configure CMake
        if: runner.os == 'macOS'
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DENABLE_ALL_WARNINGS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Run h3daemon
        working-directory: ${{github.workspace}}/build
        run: |
          loginctl enable-linger 1001
          curl -fsSL "https://app.danilohorta.me/h3daemon" > h3daemon
          chmod +x h3daemon
          ./h3daemon start test/assets/ross.1.hmm --name=h3daemon_51371 --port=51371 --yes
          ./h3daemon start test/assets/ross.2.hmm --name=h3daemon_51372 --port=51372 --yes
          ./h3daemon start test/assets/ross.3.hmm --name=h3daemon_51373 --port=51373 --yes
          ./h3daemon start test/assets/ross.4.hmm --name=h3daemon_51374 --port=51374 --yes
          ./h3daemon start test/assets/ross.5.hmm --name=h3daemon_51375 --port=51375 --yes

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --rerun-failed --output-on-failure
