name: Test

on: push

jobs:
  test:
    name: Test on ${{ matrix.os }} with build type ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        if: runner.os == 'Linux'
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DUSE_SANITIZER='Address;Undefined' -DENABLE_ALL_WARNINGS=ON

      - name: Configure CMake
        if: runner.os == 'macOS'
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DENABLE_ALL_WARNINGS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Run h3daemon
        working-directory: ${{github.workspace}}/build
        run: |
          loginctl enable-linger 1001
          curl -fsSL "https://app.danilohorta.me/h3daemon" | bash -s -- start test/assets/ross.5.hmm --name=h3daemon_51375 --port=51375 --yes

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --rerun-failed --output-on-failure
