name: Test

on: push

jobs:
  test:
    name: Test with build type ${{ matrix.build_type }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v3

      - name: Apt update
        run: sudo apt-get update

      - name: Install libcurl4
        run: sudo apt-get install -y libcurl4 libcurl4-openssl-dev

      - name: Install openssl
        run: sudo apt-get install -y libssl-dev

      - name: Install nng
        run: sudo apt-get install -y libnng1 libnng-dev

      - name: Install python
        run: sudo apt-get install -y python3-venv python3-pip

      - name: Install git
        run: sudo apt-get install -y git

      - name: Install cmake
        run: sudo apt-get install -y cmake

      - name: Install pipx
        run: python3 -m pip install --user -U pipx

      - name: Install eviltest
        run: curl -fsSL "https://app.danilohorta.me/eviltest" | bash

      - name: Setup eviltest path
        run: |
          echo "$HOME/.bats/bin" >> $GITHUB_PATH
          echo "BATS_LIB_PATH=$HOME/.bats/lib" >> $GITHUB_ENV

      - name: Configure CMake
        if: runner.os == 'Linux'
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DUSE_SANITIZER='Address;Undefined' -DENABLE_ALL_WARNINGS=ON

      - name: Configure CMake
        if: runner.os == 'macOS'
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DENABLE_ALL_WARNINGS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --rerun-failed --output-on-failure
